import type { Destination } from "@/components/DestinationCard";

export type Region = {
  id: string;
  label: string;
  note: string;
  ids: string[];
};

// Structured with a `slug` on every entry so /destinations/[slug] detail
// pages can look each one up directly. Entries with no `image` yet render
// the shared "photo coming soon" placeholder (see DestinationCard.tsx)
// instead of a broken image — drop a real file in /public/Images/tours/
// and set `image` here to activate it.
export const DESTINATIONS: Destination[] = [
  // ---- Hunza Valley: eight of the valley's real, named landmarks instead
  // of one flat "Hunza Valley" card ----
  {
    id: "karimabad",
    slug: "karimabad",
    name: "Karimabad",
    blurb: "The heart of Hunza — terraced rooftops, apricot orchards, and clear views up to Rakaposhi and Ultar Sar.",
    image: "/Images/tours/hunza-valley.png",
    tag: "Discover Karimabad",
    href: "/destinations/karimabad",
    altitude: "2,200 m",
    category: "valleys",
    badge: "Most Popular",
  },
  {
    id: "baltit-fort",
    slug: "baltit-fort",
    name: "Baltit Fort",
    blurb: "A 700-year-old fort above Karimabad, once home to the Mirs of Hunza, with the whole valley spread out below.",
    image: "/Images/tours/baltit-fort.png",
    tag: "Discover Baltit Fort",
    href: "/destinations/baltit-fort",
    altitude: "2,220 m",
    category: "cultural",
    badge: "Cultural Heritage",
  },
  {
    id: "altit-fort",
    slug: "altit-fort",
    name: "Altit Fort",
    blurb: "The oldest monument in Hunza, perched on a sheer cliff above the river since the 11th century.",
    image: "/Images/tours/gilgit_fort_upscaled.png",
    tag: "Discover Altit Fort",
    href: "/destinations/altit-fort",
    altitude: "2,100 m",
    category: "cultural",
  },
  {
    id: "attabad-lake",
    slug: "attabad-lake",
    name: "Attabad Lake",
    blurb: "A brilliant turquoise lake born from a 2010 landslide, now crossed by boat beneath the Karakoram Highway.",
    image: "/Images/tours/attabad-lake.png",
    tag: "Discover Attabad Lake",
    href: "/destinations/attabad-lake",
    altitude: "2,560 m",
    category: "lakes",
    badge: "Lake",
  },
  {
    id: "passu-cones",
    slug: "passu-cones",
    name: "Passu Cones",
    blurb: "Jagged cathedral peaks rising straight from the valley floor — one of the most photographed skylines in the north.",
    image: "/Images/tours/passu-cones.jpg",
    tag: "Discover Passu Cones",
    href: "/destinations/passu-cones",
    altitude: "2,400 m",
    category: "mountains",
  },
  {
    id: "khunjerab-pass",
    slug: "khunjerab-pass",
    name: "Khunjerab Pass",
    blurb: "The highest paved border crossing in the world, where the Karakoram Highway meets China at 4,700 metres.",
    image: "/Images/tours/khunjerab.png",
    tag: "Discover Khunjerab Pass",
    href: "/destinations/khunjerab-pass",
    altitude: "4,700 m",
    category: "national-parks",
    badge: "High Altitude",
  },
  {
    id: "borith-lake",
    slug: "borith-lake",
    name: "Borith Lake",
    blurb: "A saline lake above Hussaini, ringed by willow and sea buckthorn, with views up to the Passu glaciers.",
    tag: "Discover Borith Lake",
    href: "/destinations/borith-lake",
    altitude: "2,600 m",
    category: "lakes",
  },
  {
    id: "shimshal-valley",
    slug: "shimshal-valley",
    name: "Shimshal Valley",
    blurb: "One of the most remote settlements in the Karakoram, reached by a cliffside road above the Shimshal River.",
    tag: "Discover Shimshal Valley",
    href: "/destinations/shimshal-valley",
    altitude: "3,100 m",
    category: "valleys",
    badge: "Remote",
  },
  // ---- Nagar Valley: four named places across the valley ----
  {
    id: "rakaposhi-base-camp",
    slug: "rakaposhi-base-camp",
    name: "Rakaposhi Base Camp",
    blurb: "A trek through pine forest and high pasture to the foot of Rakaposhi, one of the world's most dramatic peaks.",
    image: "/Images/tours/rakaposhi-trek.jpg",
    tag: "Discover Rakaposhi Base Camp",
    href: "/destinations/rakaposhi-base-camp",
    altitude: "3,200 m",
    category: "trekking",
    badge: "Adventure",
  },
  {
    id: "hopar-glacier",
    slug: "hopar-glacier",
    name: "Hopar Glacier",
    blurb: "A glacier valley within walking distance of the village, framed by Diran and Spantik on either side.",
    tag: "Discover Hopar Glacier",
    href: "/destinations/hopar-glacier",
    altitude: "2,700 m",
    category: "mountains",
  },
  {
    id: "rush-lake",
    slug: "rush-lake",
    name: "Rush Lake",
    blurb: "One of the highest alpine lakes in the world, reached by a high-altitude trek above Nagar's glaciers.",
    tag: "Discover Rush Lake",
    href: "/destinations/rush-lake",
    altitude: "4,694 m",
    category: "trekking",
    badge: "High Altitude",
  },
  {
    id: "minapin-glacier",
    slug: "minapin-glacier",
    name: "Minapin Glacier",
    blurb: "A classic trailhead into the Karakoram, with Diran Peak rising directly above the ice.",
    tag: "Discover Minapin Glacier",
    href: "/destinations/minapin-glacier",
    altitude: "2,800 m",
    category: "trekking",
  },
  // ---- Gilgit & Ghizer: four named places ----
  {
    id: "ghizer-valley",
    slug: "ghizer-valley",
    name: "Ghizer Valley",
    blurb:
      "A peaceful landscape of turquoise rivers, mountain villages, and quiet valleys shaped by the waters of the north.",
    tag: "Discover Ghizer Valley",
    href: "/destinations/ghizer-valley",
    altitude: "2,150 m",
    category: "valleys",
  },
  {
    id: "yasin-valley",
    slug: "yasin-valley",
    name: "Yasin Valley",
    blurb: "A secluded valley of green fields, traditional villages, and dramatic mountain scenery.",
    tag: "Discover Yasin Valley",
    href: "/destinations/yasin-valley",
    altitude: "2,500 m",
    category: "valleys",
  },
  {
    id: "phander-valley",
    slug: "phander-valley",
    name: "Phander Valley",
    blurb: "A hidden valley of lakes and orchards in Ghizer, where still turquoise water sits beneath quiet peaks.",
    tag: "Discover Phander Valley",
    href: "/destinations/phander-valley",
    altitude: "2,900 m",
    category: "lakes",
  },
  {
    id: "naltar-valley",
    slug: "naltar-valley",
    name: "Naltar Valley",
    blurb: "Pine forests and a chain of colourful alpine lakes make Naltar one of the north's most vivid landscapes.",
    tag: "Discover Naltar Valley",
    href: "/destinations/naltar-valley",
    altitude: "2,800 m",
    category: "valleys",
    badge: "Seasonal",
  },
  // ---- Baltistan: four named places ----
  {
    id: "skardu-katpana",
    slug: "skardu-katpana",
    name: "Skardu & Katpana",
    blurb: "Cold desert dunes beside turquoise lakes, surrounded by dramatic mountain scenery.",
    image: "/Images/tours/sarfaranga-desert.png",
    tag: "Discover Skardu & Katpana",
    href: "/destinations/skardu-katpana",
    altitude: "2,230 m",
    category: "mountains",
  },
  {
    id: "shigar-valley",
    slug: "shigar-valley",
    name: "Shigar Valley",
    blurb: "A historic valley of stone villages, fertile fields, and gateways to the high mountains of Baltistan.",
    image: "/Images/tours/shigar-fort.png",
    tag: "Discover Shigar Valley",
    href: "/destinations/shigar-valley",
    altitude: "2,290 m",
    category: "cultural",
  },
  {
    id: "deosai-plains",
    slug: "deosai-plains",
    name: "Deosai Plains",
    blurb: "The Land of Giants — vast alpine plains where wild landscapes stretch beneath an endless sky.",
    image: "/Images/tours/deosai-plains.png",
    tag: "Discover Deosai Plains",
    href: "/destinations/deosai-plains",
    altitude: "4,114 m",
    category: "national-parks",
    badge: "Wildlife",
  },
  {
    id: "kachura-lake",
    slug: "kachura-lake",
    name: "Kachura Lake",
    blurb: "A still turquoise lake near Skardu, its glassy water mirroring the pine forest and cliffs around it.",
    tag: "Discover Kachura Lake",
    href: "/destinations/kachura-lake",
    altitude: "2,500 m",
    category: "lakes",
  },
  // ---- Diamer & Astore: four named places ----
  {
    id: "fairy-meadows",
    slug: "fairy-meadows",
    name: "Fairy Meadows",
    blurb: "Alpine meadows at the foot of Nanga Parbat, wrapped in pine forest and morning mist.",
    image: "/Images/tours/Fairy-meadows.png",
    tag: "Discover Fairy Meadows",
    href: "/destinations/fairy-meadows",
    altitude: "3,300 m",
    category: "trekking",
  },
  {
    id: "rama-lake",
    slug: "rama-lake",
    name: "Rama Lake",
    blurb: "A still alpine lake ringed by pine forest, framed by uninterrupted views of Nanga Parbat rising above.",
    tag: "Discover Rama Lake",
    href: "/destinations/rama-lake",
    altitude: "3,300 m",
    category: "lakes",
  },
  {
    id: "harmosh-valley",
    slug: "harmosh-valley",
    name: "Harmosh Valley",
    blurb: "A remote glacial valley below Haramosh Peak, reached through pine forest and high pasture far from the highway.",
    tag: "Discover Harmosh Valley",
    href: "/destinations/harmosh-valley",
    altitude: "3,100 m",
    category: "trekking",
  },
  {
    id: "rupal-valley",
    slug: "rupal-valley",
    name: "Rupal Valley",
    blurb: "Gateway to Nanga Parbat's Rupal Face, one of the tallest mountain walls on earth, deep in Astore district.",
    tag: "Discover Rupal Valley",
    href: "/destinations/rupal-valley",
    altitude: "3,200 m",
    category: "mountains",
  },
];

export const REGIONS: Region[] = [
  {
    id: "hunza",
    label: "Hunza Valley",
    note: "Orchards, forts, and the valley's iconic skyline",
    ids: [
      "karimabad",
      "baltit-fort",
      "altit-fort",
      "attabad-lake",
      "passu-cones",
      "khunjerab-pass",
      "borith-lake",
      "shimshal-valley",
    ],
  },
  {
    id: "nagar",
    label: "Nagar Valley",
    note: "Glaciers, high pastures, and the road to Rakaposhi",
    ids: ["rakaposhi-base-camp", "hopar-glacier", "rush-lake", "minapin-glacier"],
  },
  {
    id: "gilgit-ghizer",
    label: "Gilgit & Ghizer",
    note: "Rivers, lakes, and quiet villages",
    ids: ["ghizer-valley", "yasin-valley", "phander-valley", "naltar-valley"],
  },
  {
    id: "baltistan",
    label: "Baltistan",
    note: "Deserts, plains, and stone forts",
    ids: ["skardu-katpana", "shigar-valley", "deosai-plains", "kachura-lake"],
  },
  {
    id: "diamer-astore",
    label: "Diamer & Astore",
    note: "Meadows, valleys, and lakes beneath the Killer Mountain",
    ids: ["fairy-meadows", "rama-lake", "harmosh-valley", "rupal-valley"],
  },
];

export function getDestination(slug: string): Destination | undefined {
  return DESTINATIONS.find((d) => d.slug === slug);
}

export function getRegionFor(id: string): Region | undefined {
  return REGIONS.find((r) => r.ids.includes(id));
}
